/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sptech.banco.saver;

import java.io.IOException;
import java.util.List;
import java.util.TimerTask;

/**
 *
 * @author aluno
 */
public class menuSaver extends javax.swing.JFrame {

    /**
     * Creates new form menuSaver
     */
    public menuSaver() {
        initComponents();
    }
    private Usuario user;
    public menuSaver(Usuario user) {
        this.user = user;
        initComponents();
        this.Insercoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnT1 = new javax.swing.JButton();
        btnT2 = new javax.swing.JButton();
        btnSairMenu = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Saver.png"))); // NOI18N

        btnT1.setBackground(new java.awt.Color(51, 102, 255));
        btnT1.setFont(new java.awt.Font("Kalimati", 1, 14)); // NOI18N
        btnT1.setText("Monitor CPU");
        btnT1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, null));
        btnT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnT1ActionPerformed(evt);
            }
        });

        btnT2.setBackground(new java.awt.Color(51, 102, 255));
        btnT2.setFont(new java.awt.Font("Kalimati", 1, 14)); // NOI18N
        btnT2.setText("Monitor RAM");
        btnT2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, null));
        btnT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnT2ActionPerformed(evt);
            }
        });

        btnSairMenu.setBackground(new java.awt.Color(0, 153, 255));
        btnSairMenu.setFont(new java.awt.Font("Kalimati", 1, 14)); // NOI18N
        btnSairMenu.setText("Sair");
        btnSairMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairMenuActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnSairMenu)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnT1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(btnT2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnT1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnT2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(btnSairMenu)
                .addGap(21, 21, 21))
        );

        jTextField1.setText(String.format("Olá %s", user.getNome()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairMenuActionPerformed
        // TODO add your handling code here:

        new java.util.Timer().schedule(new TimerTask(){
            @Override
            public void run() {
                dispose();
                new swingSaver().setVisible(true);
            }
        },1000*1);
    }//GEN-LAST:event_btnSairMenuActionPerformed

    private void btnT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnT1ActionPerformed
        // TODO add your handling code here:

        new java.util.Timer().schedule(new TimerTask(){
            @Override
            public void run() {
                dispose();
                new Tela1(user).setVisible(true);
            }
        },1000*1);
    }//GEN-LAST:event_btnT1ActionPerformed

    private void btnT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnT2ActionPerformed
        // TODO add your handling code here:

        new java.util.Timer().schedule(new TimerTask(){
            @Override
            public void run() {
                dispose();
                new Tela2(user).setVisible(true);
            }
        },1000*1);
    }//GEN-LAST:event_btnT2ActionPerformed

    private void Insercoes() {
        ColetaDeDados coleta = new ColetaDeDados(user);
        List idComputador = coleta.getIdComputador();
        List idRack = coleta.getIdRack();
        AppSlack slack = new AppSlack();
        System.out.println(String.valueOf(idComputador.get(0)).replaceAll("[^0-9]+", ""));
        System.out.println(String.valueOf(idRack.get(0)).replaceAll("[^0-9]+", ""));

        new java.util.Timer().schedule(new TimerTask(){
            @Override
            public void run() {
                try {
                    coleta.gerarLog();
                } catch (IOException | InterruptedException e) {
                    throw new RuntimeException(e);
                }
                try {
                    slack.mandaMensagemSlack(user);
                } catch (IOException | InterruptedException e) {
                    throw new RuntimeException(e);
                }
                coleta.insercaoDados(String.valueOf(idComputador.get(0)).replaceAll("[^0-9]+", ""),
                        String.valueOf(idRack.get(0)).replaceAll("[^0-9]+", ""));
            }
        },0,1000*2);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuSaver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuSaver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuSaver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuSaver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                new menuSaver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSairMenu;
    private javax.swing.JButton btnT1;
    private javax.swing.JButton btnT2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
